const engLang = {
  'pull_to_refresh': 'Pull to refresh',
  'dogs_finder': 'Dogs Finder',
  'failed_to_load': 'Failed to load',
  'try_again': 'Please try again',
  'picked_for_you': 'Randomly picked for you',
  'images_list': 'Breed of your choice',
  'breeds': 'Breeds',
  'sub_breed': 'We have sub breed for ',
  'no_sub_breed': 'No sub breed found for ',
  'no_internet': "No Internet!",
  'connect_wifi_data': "Connect wifi or turn on data",
  'failed_or_check_internet': "Failed to load\nor\nCheck internet connection !",
  'reached_end': 'You have reached to the end !',
};
